### ISSUE TITLE
can't run [bundle exec rake install]

### ISSUE THREAD

**Issue by minwe** [r7kamura/cssdoc#1]
``` bash
E:\cssdoc\cssdoc>bundle exec rake install --trace
** Invoke install (first_time)
** Invoke build (first_time)
** Execute build
cssdoc 0.0.1 built to pkg/cssdoc-0.0.1.gem.
** Execute install
rake aborted!
Couldn't install gem, run `gem install E:/cssdoc/cssdoc/pkg/cssdoc-0.0.1.gem' fo
r more detailed output
d:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:
70:in `install_gem'
d:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/gem_helper.rb:
45:in `block in install'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:228:in `call'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:228:in `block in execute'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:223:in `each'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:223:in `execute'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:166:in `block in invoke_with_call_cha
in'
d:/Ruby200-x64/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:159:in `invoke_with_call_chain'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/task.rb:152:in `invoke'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:143:in `invoke_task'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `block (2 levels) in to
p_level'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `each'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:101:in `block in top_level'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:110:in `run_with_threads'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:95:in `top_level'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:73:in `block in run'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_han
dling'
d:/Ruby200-x64/lib/ruby/2.0.0/rake/application.rb:70:in `run'
d:/Ruby200-x64/bin/rake:37:in `<main>'
Tasks: TOP => install
```

**Comment by r7kamura** [comment]
It seems that `rake build` succeeded, but `gem install pkg/cssdoc-0.0.1.gem --local` failed for any reason.
1. Try `gem install pkg/cssdoc-0.0.1.gem --local` or `rake install` (without `bundle exec`)
2. Could you tell me more details about your environment? (e.g., OS, `ruby -v`)

**Comment by minwe** [comment]
1.

``` bash
E:\cssdoc\cssdoc>gem install pkg/cssdoc-0.0.1.gem --local
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: cssdoc requires nokogiri (>= 0)
```

## My OS is `Widnows 7 64 bit`

 `ruby 2.0.0p247 (2013-06-27) [x64-mingw32]`

**Comment by r7kamura** [comment]
hmm... the error message obviously tells that you need to install the dependent [Nokogiri](https://github.com/sparklemotion/nokogiri) gem. Could you try to install nokogiri gem? With windows, you might want to install libxml2 & libxslt too.
